apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-01
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # nfs: # recomendable en servidores NFS diferentes
  #   server: lab1.dockerlabs.tk # dominio o ip del servidor nfs
  #   path: /srv/nfs/mydata # path servidor
  hostPath:
    path: /data/01
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-02
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # nfs:
  #   server: lab1.dockerlabs.tk
  #   path: /srv/nfs/mydata
  hostPath:
    path: /data/02
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-03
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # nfs:
  #   server: lab1.dockerlabs.tk
  #   path: /srv/nfs/mydata
  hostPath:
    path: /data/03
    type: DirectoryOrCreate
