apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
spec:
  selector:
    matchLabels:
      app: podinfo2
  template:
    metadata:
      labels:
        app: podinfo2
    spec:
      containers:
      - name: podinfo2
        image: stefanprodan/podinfo
        ports:
        - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo2
spec:
  ports:
    - port: 80
      targetPort: 9898
      nodePort: 30001
  selector:
    app: podinfo2
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo2
spec:
  ingressClassName: nginx
  rules:
    - host: "carlosh2.kubelabs.tk"
      http:
        paths:
          - backend:
              service:
                name: podinfo2
                port:
                  number: 80
            path: /
            pathType: Prefix
