apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dashboard
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: web-dashboard
    spec:
      serviceAccountName: dashboard-sa
      containers:
      - image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard
        imagePullPolicy: Always
        name: web-dashboard
        ports:
        - containerPort: 8080
          protocol: TCP
        resource:
---
apiVersion: v1
kind: Service
metadata:
  name: web-dashboard
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: web-dashboard
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-dashboard
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: cp01.josemcq.kubelabs.tk
      http:
        paths:
          - backend:
              service:
                name: web-dashboard
                port:
                  number: 80
            path: /
            pathType: Prefix

