apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-read-access
rules:
- apiGroups: [""]
  resources: ["pods","configmaps","services","events","namespaces","nodes","limitranges","persistentvolumes","persistenttvolumeclaims","resourcequotas"]
  verbs: ["get", "watch", "list"]
- apiGroups:
    - apps
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-users
  namespace: default
subjects:
- kind: User
  name: <USER> # User name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-read-access
  apiGroup: rbac.authorization.k8s.io
# k create clusterrolebinding kube-support-kube-reader --clusterrole=kube-reader-cluster-role --user=kube-support
# https://gist.github.com/karthik101/201374aee2ebea25ddf6c723858568be#file-readonly-user-for-kubernetes-dashboard-md
