kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-users
  namespace: default
subjects:
- kind: User
  name: <USER> # User name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer # Role name
  apiGroup: rbac.authorization.k8s.io
