apiVersion: apps/v1
kind: Deployment

metadata:
  name: helmdemo

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pod-helm-app

  template:
    metadata:
      name: helmdemo
      labels:
        app: pod-helm-app

    spec:
      containers:
        - name: helm-demo
          image: cachac/kube-labs
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
