kind: Service
apiVersion: v1
metadata:
  name: svc-helm-app
spec:
  type: NodePort
  selector:
    app: pod-helm-app
  ports:
    - protocol: TCP
      name: main
      port: 80
      targetPort: 8080
			nodePort: 30080
