kind: Service
apiVersion: v1
metadata:
  # name: svc-helm-app
	  name: {{ .Values.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: pod-helm-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
			# targetPort: {{ .Values.targetPort }}

