apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kubelabs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubelabs
  minReplicas: 1
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 35

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
