apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelabs
spec:
  selector:
    matchLabels:
      app: kubelabs
  template:
    metadata:
      labels:
        app: kubelabs
    spec:
      containers:
      - name: kubelabs
        image: cachac/kube-labs
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kubelabs
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: kubelabs
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubelabs
spec:
  ingressClassName: nginx
  rules:
    - host: USERLAB.kubelabs.tk
      http:
        paths:
          - backend:
              service:
                name: kubelabs
                port:
                  number: 80
            path: /
            pathType: Prefix
